"""Repository ports for the News Intelligence & Community Intelligence Platform's persistence
store (Milestone 8)."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.intelligence.domain.entities import (
    CommunityPost,
    CommunityTopic,
    ImpactScore,
    IntelligenceSyncCheckpoint,
    IntelligenceSyncRun,
    NewsArticle,
    NewsEvent,
    NewsSource,
    SentimentResult,
    Summary,
    SourceReliabilityScore,
)
from modules.intelligence.domain.value_objects import (
    CommunityPlatform,
    CommunityPostId,
    CommunityTopicId,
    ImpactScoreId,
    IntelligenceChannelType,
    IntelligenceSyncRunId,
    NewsArticleId,
    NewsEventId,
    NewsSourceId,
    NewsSourceType,
    SentimentResultId,
    SummaryId,
    SummaryType,
)


class NewsSourceRepositoryPort(Protocol):
    async def get(self, source_id: NewsSourceId) -> NewsSource | None: ...
    async def get_by_url(self, url: str) -> NewsSource | None: ...
    async def list_by_type(self, source_type: NewsSourceType) -> list[NewsSource]: ...
    async def list_all(self) -> list[NewsSource]: ...
    async def upsert(self, source: NewsSource) -> NewsSource: ...


class NewsArticleRepositoryPort(Protocol):
    async def get(self, article_id: NewsArticleId) -> NewsArticle | None: ...
    async def get_by_content_hash(self, content_hash: str) -> NewsArticle | None: ...
    async def get_by_url(self, url: str) -> NewsArticle | None: ...
    async def upsert(self, article: NewsArticle) -> NewsArticle: ...
    async def search(
        self, query: str | None = None, source_id: NewsSourceId | None = None, limit: int = 50
    ) -> list[NewsArticle]: ...
    async def list_since(self, since: datetime, limit: int = 200) -> list[NewsArticle]: ...
    async def count_all(self) -> int: ...


class NewsEventRepositoryPort(Protocol):
    async def get(self, event_id: NewsEventId) -> NewsEvent | None: ...
    async def record(self, event: NewsEvent) -> NewsEvent: ...
    async def list_for_entity(self, entity_ref: str, limit: int = 50) -> list[NewsEvent]: ...
    async def list_timeline(
        self, since: datetime | None = None, until: datetime | None = None, limit: int = 100
    ) -> list[NewsEvent]: ...


class SourceReliabilityRepositoryPort(Protocol):
    async def get_for_source(self, source_id: NewsSourceId) -> SourceReliabilityScore | None: ...
    async def upsert(self, score: SourceReliabilityScore) -> SourceReliabilityScore: ...
    async def list_all(self) -> list[SourceReliabilityScore]: ...


class SentimentResultRepositoryPort(Protocol):
    async def record(self, result: SentimentResult) -> SentimentResult: ...
    async def list_for_entity(self, entity_ref: str, limit: int = 50) -> list[SentimentResult]: ...


class ImpactScoreRepositoryPort(Protocol):
    async def get(self, impact_id: ImpactScoreId) -> ImpactScore | None: ...
    async def record(self, score: ImpactScore) -> ImpactScore: ...
    async def get_for_event(self, news_event_id: NewsEventId) -> ImpactScore | None: ...
    async def list_recent(self, limit: int = 50) -> list[ImpactScore]: ...


class SummaryRepositoryPort(Protocol):
    async def get(self, summary_id: SummaryId) -> Summary | None: ...
    async def record(self, summary: Summary) -> Summary: ...
    async def get_latest(self, subject_ref: str, summary_type: SummaryType) -> Summary | None: ...


class CommunityPostRepositoryPort(Protocol):
    async def get_by_external_id(self, platform: CommunityPlatform, external_id: str) -> CommunityPost | None: ...
    async def upsert(self, post: CommunityPost) -> CommunityPost: ...
    async def list_recent(self, platform: CommunityPlatform | None = None, limit: int = 100) -> list[CommunityPost]: ...


class CommunityTopicRepositoryPort(Protocol):
    async def get(self, topic_id: CommunityTopicId) -> CommunityTopic | None: ...
    async def get_by_label(self, platform: CommunityPlatform, topic_label: str) -> CommunityTopic | None: ...
    async def upsert(self, topic: CommunityTopic) -> CommunityTopic: ...
    async def list_all(self, platform: CommunityPlatform | None = None) -> list[CommunityTopic]: ...


class IntelligenceSyncRunRepositoryPort(Protocol):
    async def record(self, run: IntelligenceSyncRun) -> IntelligenceSyncRun: ...
    async def update(self, run: IntelligenceSyncRun) -> IntelligenceSyncRun: ...
    async def get(self, run_id: IntelligenceSyncRunId) -> IntelligenceSyncRun | None: ...
    async def list_recent(
        self, channel_type: IntelligenceChannelType | None = None, limit: int = 50
    ) -> list[IntelligenceSyncRun]: ...


class IntelligenceSyncCheckpointRepositoryPort(Protocol):
    async def get(
        self, channel_type: IntelligenceChannelType, channel_key: str
    ) -> IntelligenceSyncCheckpoint | None: ...
    async def upsert(self, checkpoint: IntelligenceSyncCheckpoint) -> IntelligenceSyncCheckpoint: ...
