"""Repository ports for the Knowledge Graph's relational store
(docs/decisions.md ADR-005 — relational KG, not a dedicated graph DB, for v1)."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.knowledge_graph.domain.entities import KGEdge, KGNode
from modules.knowledge_graph.domain.value_objects import EdgeType, KGEdgeId, KGNodeId, NodeType


class KGNodeRepositoryPort(Protocol):
    async def get(self, node_id: KGNodeId) -> KGNode | None: ...
    async def get_by_entity_ref(self, node_type: NodeType, entity_ref: str) -> KGNode | None: ...
    async def list_by_type(self, node_type: NodeType) -> list[KGNode]: ...
    async def upsert(self, node: KGNode) -> KGNode: ...

    async def count_by_type(self, node_type: NodeType) -> int:
        """Row count for this node type via a SQL COUNT, not `len(await list_by_type(...))` —
        Graph Monitoring's scale metrics (Milestone 7) need only the count, and `list_by_type`
        fetching and ORM-mapping every row of every type on a real-scale graph was the dominant
        cost of the public `platform-summary`/`knowledge-graph-preview` endpoints. Additive: no
        existing method changed."""
        ...


class KGEdgeRepositoryPort(Protocol):
    async def get_current(
        self, from_node_id: KGNodeId, to_node_id: KGNodeId, edge_type: EdgeType
    ) -> KGEdge | None: ...
    async def list_from(self, from_node_id: KGNodeId, edge_type: EdgeType | None = None) -> list[KGEdge]: ...
    async def list_to(self, to_node_id: KGNodeId, edge_type: EdgeType | None = None) -> list[KGEdge]: ...
    async def list_by_type(self, edge_type: EdgeType, limit: int = 5000) -> list[KGEdge]: ...
    async def upsert(self, edge: KGEdge) -> KGEdge: ...
    async def close(self, edge_id: KGEdgeId, valid_to: datetime) -> KGEdge | None: ...
    async def delete(self, edge_id: KGEdgeId) -> bool: ...

    async def count_by_type(self, edge_type: EdgeType) -> int:
        """Row count for this edge type via a SQL COUNT — mirrors
        `KGNodeRepositoryPort.count_by_type`; see that docstring. Additive: no existing method
        changed."""
        ...
