"""Repository ports for the Knowledge Graph's relational store
(docs/decisions.md ADR-005 — relational KG, not a dedicated graph DB, for v1)."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.knowledge_graph.domain.entities import KGEdge, KGNode
from modules.knowledge_graph.domain.value_objects import EdgeType, KGEdgeId, KGNodeId, NodeType


class KGNodeRepositoryPort(Protocol):
    async def get(self, node_id: KGNodeId) -> KGNode | None: ...
    async def get_by_entity_ref(self, node_type: NodeType, entity_ref: str) -> KGNode | None: ...
    async def list_by_type(self, node_type: NodeType) -> list[KGNode]: ...
    async def upsert(self, node: KGNode) -> KGNode: ...


class KGEdgeRepositoryPort(Protocol):
    async def get_current(
        self, from_node_id: KGNodeId, to_node_id: KGNodeId, edge_type: EdgeType
    ) -> KGEdge | None: ...
    async def list_from(self, from_node_id: KGNodeId, edge_type: EdgeType | None = None) -> list[KGEdge]: ...
    async def list_to(self, to_node_id: KGNodeId, edge_type: EdgeType | None = None) -> list[KGEdge]: ...
    async def list_by_type(self, edge_type: EdgeType, limit: int = 5000) -> list[KGEdge]: ...
    async def upsert(self, edge: KGEdge) -> KGEdge: ...
    async def close(self, edge_id: KGEdgeId, valid_to: datetime) -> KGEdge | None: ...
    async def delete(self, edge_id: KGEdgeId) -> bool: ...
