"""Repository ports for the Subscription/Billing bounded context."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.billing.domain.entities import Entitlement, Plan, Subscription, UsageCounter
from modules.billing.domain.payment import PendingCheckout
from modules.billing.domain.value_objects import PendingCheckoutId, PlanId, SubjectType, SubscriptionId


class PlanRepositoryPort(Protocol):
    async def get(self, plan_id: PlanId) -> Plan | None: ...
    async def get_by_key(self, key: str) -> Plan | None: ...
    async def list_all(self) -> list[Plan]: ...
    async def upsert(self, plan: Plan) -> Plan: ...


class EntitlementRepositoryPort(Protocol):
    async def list_by_plan(self, plan_id: PlanId) -> list[Entitlement]: ...
    async def get(self, plan_id: PlanId, feature_key: str) -> Entitlement | None: ...
    async def upsert(self, entitlement: Entitlement) -> Entitlement: ...


class SubscriptionRepositoryPort(Protocol):
    async def get(self, subscription_id: SubscriptionId) -> Subscription | None: ...
    async def get_active_for_subject(self, subject_type: SubjectType, subject_id: str) -> Subscription | None: ...
    async def upsert(self, subscription: Subscription) -> Subscription: ...


class UsageCounterRepositoryPort(Protocol):
    async def get(
        self, subject_type: SubjectType, subject_id: str, feature_key: str, window_key: str
    ) -> UsageCounter | None: ...
    async def upsert(self, counter: UsageCounter) -> UsageCounter: ...


class PendingCheckoutRepositoryPort(Protocol):
    async def get(self, checkout_id: PendingCheckoutId) -> PendingCheckout | None: ...
    async def get_by_reference(self, reference: str) -> PendingCheckout | None: ...
    async def get_by_provider_charge_id(self, provider_charge_id: str) -> PendingCheckout | None: ...
    async def upsert(self, checkout: PendingCheckout) -> PendingCheckout: ...


class ProcessedPaymentEventRepositoryPort(Protocol):
    """Webhook-delivery idempotency — the same event id must never be processed twice, no
    matter how many times the provider redelivers it (docs constitution: webhook processing
    must be idempotent)."""

    async def already_processed(self, provider: str, event_id: str) -> bool: ...
    async def mark_processed(self, provider: str, event_id: str, now: datetime) -> None: ...
