"""Repository ports for the Subscription/Billing bounded context."""

from __future__ import annotations

from typing import Protocol

from modules.billing.domain.entities import Entitlement, Plan, Subscription, UsageCounter
from modules.billing.domain.value_objects import PlanId, SubjectType, SubscriptionId


class PlanRepositoryPort(Protocol):
    async def get(self, plan_id: PlanId) -> Plan | None: ...
    async def get_by_key(self, key: str) -> Plan | None: ...
    async def list_all(self) -> list[Plan]: ...
    async def upsert(self, plan: Plan) -> Plan: ...


class EntitlementRepositoryPort(Protocol):
    async def list_by_plan(self, plan_id: PlanId) -> list[Entitlement]: ...
    async def get(self, plan_id: PlanId, feature_key: str) -> Entitlement | None: ...
    async def upsert(self, entitlement: Entitlement) -> Entitlement: ...


class SubscriptionRepositoryPort(Protocol):
    async def get(self, subscription_id: SubscriptionId) -> Subscription | None: ...
    async def get_active_for_subject(self, subject_type: SubjectType, subject_id: str) -> Subscription | None: ...
    async def upsert(self, subscription: Subscription) -> Subscription: ...


class UsageCounterRepositoryPort(Protocol):
    async def get(
        self, subject_type: SubjectType, subject_id: str, feature_key: str, window_key: str
    ) -> UsageCounter | None: ...
    async def upsert(self, counter: UsageCounter) -> UsageCounter: ...
