"""Repository ports for the Webhook Infrastructure bounded context."""

from __future__ import annotations

from typing import Protocol

from modules.webhooks.domain.entities import WebhookDelivery, WebhookEndpoint
from modules.webhooks.domain.value_objects import WebhookDeliveryId, WebhookEndpointId


class WebhookEndpointRepositoryPort(Protocol):
    async def get(self, endpoint_id: WebhookEndpointId) -> WebhookEndpoint | None: ...
    async def list_by_organization(self, organization_id: str) -> list[WebhookEndpoint]: ...
    async def list_subscribed_to(self, event_type: str) -> list[WebhookEndpoint]: ...
    async def upsert(self, endpoint: WebhookEndpoint) -> WebhookEndpoint: ...
    async def delete(self, endpoint_id: WebhookEndpointId) -> None: ...


class WebhookDeliveryRepositoryPort(Protocol):
    async def get(self, delivery_id: WebhookDeliveryId) -> WebhookDelivery | None: ...
    async def list_by_endpoint(self, endpoint_id: WebhookEndpointId, limit: int = 100) -> list[WebhookDelivery]: ...
    async def list_pending_retries(self) -> list[WebhookDelivery]: ...
    async def upsert(self, delivery: WebhookDelivery) -> WebhookDelivery: ...
