import { Link } from 'react-router-dom'
import { Seo } from '@/components/seo/seo'
import { LegalPageLayout, LegalSection, LegalParagraph, LegalList, LegalCallout } from '@/components/marketing/legal-layout'

const TOC = [
  { id: 'overview', label: 'Overview' },
  { id: 'how-it-works', label: 'How News Intelligence works' },
  { id: 'source-verification', label: 'Source verification' },
  { id: 'ai-summarization', label: 'AI summarization' },
  { id: 'human-review', label: 'Human review' },
  { id: 'corrections', label: 'Corrections process' },
  { id: 'attribution', label: 'Source attribution' },
  { id: 'updates', label: 'Content updates' },
]

export default function EditorialPolicyPage() {
  return (
    <>
      <Seo
        title="Editorial Policy"
        description="How TitanIQ's News Intelligence summarizes sports news — source verification, AI summarization, corrections, and attribution."
        path="/editorial-policy"
      />
      <LegalPageLayout
        eyebrow="Legal"
        title="Editorial Policy"
        summary="TitanIQ is a sports intelligence platform, not a news wire. This policy explains how our News Intelligence feature works and the standards it holds to."
        lastUpdated="July 29, 2026"
        toc={TOC}
      >
        <LegalSection id="overview" title="Overview">
          <LegalParagraph>
            TitanIQ's News Intelligence surfaces the sports news relevant to matches, teams, and players you're
            tracking — but it is not a news publisher and does not reproduce articles. This policy sets out how we
            source, summarize, and attribute news, and the editorial standards behind that pipeline.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="how-it-works" title="How News Intelligence works">
          <LegalCallout tone="info">
            For every story, TitanIQ displays: the original headline, a TitanIQ-generated summary, the entities the
            story relates to, its estimated impact on the relevant prediction, its estimated impact on the
            associated confidence score, and a link back to the original source. We never reproduce full article
            text, and we never hotlink or reproduce a publisher's images — any imagery shown alongside a story is
            either TitanIQ-generated or from a properly licensed source.
          </LegalCallout>
        </LegalSection>

        <LegalSection id="source-verification" title="Source verification">
          <LegalParagraph>
            News Intelligence draws only from a curated set of sports data and news providers. Before a story
            influences the platform, its source is checked against that provider allowlist and cross-referenced
            against our structured sports data (for example, a reported injury is checked against team-sheet and
            lineup data where available) before it's reflected in a confidence or prediction impact score.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="ai-summarization" title="AI summarization">
          <LegalParagraph>
            TitanIQ Summaries are generated by our AI pipeline from licensed news metadata and headlines — never
            from scraping or reproducing full copyrighted article bodies. Summaries are written to convey what
            changed and why it matters to the prediction, not to substitute for reading the original reporting;
            every summary links to the original source so you can read the full story there.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="human-review" title="Human review">
          <LegalParagraph>
            Automated summarization is paired with ongoing human review of the pipeline's output quality — spot
            checks for accuracy, tone, and correct entity linking. High-impact stories (those materially moving a
            confidence score) are prioritized for review. We do not have reporters generating original news
            reporting; our editorial role is verification, summarization quality, and attribution — not newsgathering.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="corrections" title="Corrections process">
          <LegalParagraph>
            If a TitanIQ Summary misrepresents a source, or a source itself issues a correction, we update or
            remove the affected summary as soon as we're aware. To flag a summary for review, use the "Report" action
            on the story or email <a href="mailto:editorial@titaniq.ai" className="text-accent-primary hover:text-accent-primary-hover">editorial@titaniq.ai</a> — we investigate every
            report.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="attribution" title="Source attribution">
          <LegalParagraph>
            Every story displayed in News Intelligence links to its original publisher. We rely on attribution and
            summary/fair-use conventions, not reproduction, and take copyright seriously — see our{' '}
            <Link to="/copyright-policy" className="text-accent-primary hover:text-accent-primary-hover">Copyright Policy</Link> and{' '}
            <Link to="/dmca" className="text-accent-primary hover:text-accent-primary-hover">DMCA Policy</Link> if you believe we've used your content improperly.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="updates" title="Content updates">
          <LegalList
            items={[
              'Summaries are regenerated if the underlying story is updated by its publisher.',
              'Superseded stories (e.g. a lineup change reversed before kickoff) are marked as superseded, not deleted, to preserve the reasoning trail behind a prediction.',
              'The Knowledge Graph and confidence scores reflect the most current verified information.',
            ]}
          />
        </LegalSection>
      </LegalPageLayout>
    </>
  )
}
