import { Link } from 'react-router-dom'
import { Seo } from '@/components/seo/seo'
import { LegalPageLayout, LegalSection, LegalParagraph, LegalList, LegalCallout } from '@/components/marketing/legal-layout'

const TOC = [
  { id: 'overview', label: 'Overview' },
  { id: 'how-predictions-work', label: 'How predictions are generated' },
  { id: 'confidence-scoring', label: 'Confidence scoring' },
  { id: 'explainability', label: 'Explainability' },
  { id: 'continuous-learning', label: 'Continuous learning' },
  { id: 'knowledge-graph', label: 'Knowledge Graph' },
  { id: 'human-oversight', label: 'Human oversight' },
  { id: 'limitations', label: 'Limitations' },
  { id: 'bias-monitoring', label: 'Bias monitoring' },
  { id: 'transparency', label: 'Our transparency commitment' },
]

export default function ResponsibleAiPage() {
  return (
    <>
      <Seo
        title="Responsible AI Policy"
        description="How TitanIQ generates predictions, scores confidence, explains its reasoning, and keeps a human in the loop."
        path="/responsible-ai"
      />
      <LegalPageLayout
        eyebrow="Legal"
        title="Responsible AI Policy"
        summary="TitanIQ is built on the belief that AI-driven intelligence is only trustworthy if it's explainable, monitored, and honest about its limits. This is how we hold ourselves to that."
        lastUpdated="July 29, 2026"
        toc={TOC}
      >
        <LegalSection id="overview" title="Overview">
          <LegalParagraph>
            TitanIQ converts structured sports data, live match events, news, and community signal into explainable
            intelligence. Predictions are one output of that pipeline — not the point of it. This policy explains
            how our models work, how we keep them honest, and where their limits are.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="how-predictions-work" title="How predictions are generated">
          <LegalParagraph>
            Predictions are generated by statistical and machine-learning models trained on historical match data
            (team and player performance, head-to-head history, venue effects) and updated with live signals as a
            match approaches and unfolds (team-sheet news, market movement, and verified news impact). A prediction
            is a probability distribution over outcomes for a given market — not a single "correct answer."
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="confidence-scoring" title="Confidence scoring">
          <LegalParagraph>
            Every prediction carries a confidence score reflecting how much evidence supports it and how
            historically reliable the model has been in similar situations — not how "good" the predicted outcome
            is. A low-confidence prediction is not a worse prediction; it's an honest signal that the evidence is
            thinner or the situation is more volatile. Confidence is recalibrated continuously as new evidence
            arrives.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="explainability" title="Explainability">
          <LegalCallout tone="info">
            Every TitanIQ prediction is paired with the evidence behind it — the form, news, and community signals
            that fed the model — displayed alongside the prediction itself, not buried in a separate report.
            Predictions without a visible "why" are not something we consider finished.
          </LegalCallout>
        </LegalSection>

        <LegalSection id="continuous-learning" title="Continuous learning">
          <LegalParagraph>
            After a match concludes, actual outcomes are compared against the prediction and confidence score that
            preceded it. That evaluation feeds back into model retraining and calibration — see{' '}
            <Link to="/app/learning" className="text-accent-primary hover:text-accent-primary-hover">Learning Intelligence</Link> for the live view of this pipeline: prediction →
            validation → evaluation → Knowledge Graph update → confidence recalibration → retraining → improved
            predictions.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="knowledge-graph" title="Knowledge Graph">
          <LegalParagraph>
            TitanIQ maintains a structured Knowledge Graph of teams, players, competitions, and venues, and the
            relationships between them. This graph grounds predictions in verifiable, structured relationships
            (e.g. "this player's absence historically reduces this team's expected goals") rather than opaque
            correlations alone.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="human-oversight" title="Human oversight">
          <LegalParagraph>
            Models are monitored on an ongoing basis by our team, not left to run unsupervised. We review model
            performance, investigate confidence calibration drift, and can intervene — including suppressing a
            prediction — where data quality or a model anomaly would make an output unreliable.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="limitations" title="Limitations">
          <LegalList
            items={[
              'Sports outcomes have genuine, irreducible randomness — no model eliminates uncertainty, and high confidence is not a guarantee.',
              'Model quality depends on data quality and coverage, which varies by competition, sport, and market.',
              'Rare or unprecedented events (e.g. sudden rule changes, extreme weather) are harder for any model trained on historical patterns to anticipate.',
              'Predictions reflect information available at generation time and can become stale — always check the timestamp and confidence trend.',
            ]}
          />
        </LegalSection>

        <LegalSection id="bias-monitoring" title="Bias monitoring">
          <LegalParagraph>
            We monitor for systematic bias in our models — for example, a model consistently over- or
            under-estimating a particular league, team type, or market — using the same post-match evaluation
            pipeline that drives retraining. Where we find a bias, we treat it as a defect and correct it through
            retraining or feature changes, not by manually overriding individual outputs.
          </LegalParagraph>
        </LegalSection>

        <LegalSection id="transparency" title="Our transparency commitment">
          <LegalParagraph>
            We commit to disclosing, in plain language, how our predictions are generated and what they can and
            can't tell you; to never presenting a prediction as certain; and to being honest — including in this
            policy — about the limits of what AI can responsibly claim about the outcome of a live sporting event.
          </LegalParagraph>
        </LegalSection>
      </LegalPageLayout>
    </>
  )
}
