"""Repository ports for the Identity & Security bounded context."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.identity.domain.entities import (
    AccountLockState,
    AuditLogEntry,
    FederatedIdentity,
    PersonalAccessToken,
    Profile,
    SecurityEvent,
    Session,
    User,
)
from modules.identity.domain.value_objects import (
    Email,
    FederatedIdentityId,
    IdentityProvider,
    SessionId,
    TokenId,
    UserId,
)


class UserRepositoryPort(Protocol):
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def upsert(self, user: User) -> User: ...


class ProfileRepositoryPort(Protocol):
    async def get(self, user_id: UserId) -> Profile | None: ...
    async def upsert(self, profile: Profile) -> Profile: ...


class FederatedIdentityRepositoryPort(Protocol):
    async def get(self, identity_id: FederatedIdentityId) -> FederatedIdentity | None: ...
    async def get_by_provider(
        self, provider: IdentityProvider, provider_user_id: str
    ) -> FederatedIdentity | None: ...
    async def list_by_user(self, user_id: UserId) -> list[FederatedIdentity]: ...
    async def upsert(self, identity: FederatedIdentity) -> FederatedIdentity: ...
    async def delete(self, identity_id: FederatedIdentityId) -> None: ...


class PersonalAccessTokenRepositoryPort(Protocol):
    async def get(self, token_id: TokenId) -> PersonalAccessToken | None: ...
    async def get_by_hash(self, token_hash: str) -> PersonalAccessToken | None: ...
    async def list_by_user(self, user_id: UserId) -> list[PersonalAccessToken]: ...
    async def upsert(self, token: PersonalAccessToken) -> PersonalAccessToken: ...


class SessionRepositoryPort(Protocol):
    async def get(self, session_id: SessionId) -> Session | None: ...
    async def list_active_by_user(self, user_id: UserId) -> list[Session]: ...
    async def upsert(self, session: Session) -> Session: ...


class SecurityEventRepositoryPort(Protocol):
    async def record(self, event: SecurityEvent) -> SecurityEvent: ...
    async def list_recent_by_email(self, email: str, since: datetime) -> list[SecurityEvent]: ...
    async def list_recent_by_user(self, user_id: UserId, since: datetime) -> list[SecurityEvent]: ...


class AccountLockRepositoryPort(Protocol):
    async def get(self, user_id: UserId) -> AccountLockState | None: ...
    async def upsert(self, state: AccountLockState) -> AccountLockState: ...


class AuditLogRepositoryPort(Protocol):
    """No update/delete method by design — the audit trail is append-only."""

    async def append(self, entry: AuditLogEntry) -> AuditLogEntry: ...
    async def list_by_actor(self, actor_user_id: UserId, limit: int = 100) -> list[AuditLogEntry]: ...
    async def list_by_target(self, target_type: str, target_id: str) -> list[AuditLogEntry]: ...
