"""Repository ports for the Provider Management System."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from modules.admin.domain.entities import (
    FeatureFlag,
    ProviderCredential,
    ProviderDefinition,
    ProviderHealthCheck,
    ProviderHealthState,
    ProviderIncident,
    ProviderUsageRecord,
)
from modules.admin.domain.value_objects import CredentialId, FlagId, IncidentId, ProviderId, QuotaPeriod


class ProviderRepositoryPort(Protocol):
    async def get(self, provider_id: ProviderId) -> ProviderDefinition | None: ...
    async def get_by_key(self, key: str) -> ProviderDefinition | None: ...
    async def list_all(self) -> list[ProviderDefinition]: ...
    async def upsert(self, provider: ProviderDefinition) -> ProviderDefinition: ...


class CredentialRepositoryPort(Protocol):
    async def get(self, credential_id: CredentialId) -> ProviderCredential | None: ...
    async def list_by_provider(self, provider_id: ProviderId) -> list[ProviderCredential]: ...
    async def upsert(self, credential: ProviderCredential) -> ProviderCredential: ...
    async def delete(self, credential_id: CredentialId) -> None: ...


class UsageRepositoryPort(Protocol):
    async def get(
        self,
        provider_id: ProviderId,
        period: QuotaPeriod,
        window_key: str,
        credential_id: CredentialId | None = None,
    ) -> ProviderUsageRecord | None: ...
    async def upsert(self, record: ProviderUsageRecord) -> ProviderUsageRecord: ...


class HealthRepositoryPort(Protocol):
    async def record(self, check: ProviderHealthCheck) -> ProviderHealthCheck: ...
    async def list_recent(self, provider_id: ProviderId, limit: int = 20) -> list[ProviderHealthCheck]: ...
    async def list_since(self, provider_id: ProviderId, since: datetime) -> list[ProviderHealthCheck]: ...


class HealthStateRepositoryPort(Protocol):
    async def get(self, provider_id: ProviderId) -> ProviderHealthState | None: ...
    async def upsert(self, state: ProviderHealthState) -> ProviderHealthState: ...


class IncidentRepositoryPort(Protocol):
    async def get(self, incident_id: IncidentId) -> ProviderIncident | None: ...
    async def list_by_provider(self, provider_id: ProviderId) -> list[ProviderIncident]: ...
    async def list_open(self, provider_id: ProviderId) -> list[ProviderIncident]: ...
    async def upsert(self, incident: ProviderIncident) -> ProviderIncident: ...


class FeatureFlagRepositoryPort(Protocol):
    async def get(self, flag_id: FlagId) -> FeatureFlag | None: ...
    async def get_by_key(self, key: str) -> FeatureFlag | None: ...
    async def list_all(self) -> list[FeatureFlag]: ...
    async def upsert(self, flag: FeatureFlag) -> FeatureFlag: ...
