"""Repository ports for the Multi-Tenancy bounded context."""

from __future__ import annotations

from typing import Protocol

from modules.identity.domain.value_objects import UserId
from modules.tenancy.domain.entities import Invitation, Membership, Organization, Team
from modules.tenancy.domain.value_objects import InvitationId, MembershipId, OrganizationId, TeamId


class OrganizationRepositoryPort(Protocol):
    async def get(self, organization_id: OrganizationId) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def list_owned_by(self, owner_user_id: UserId) -> list[Organization]: ...
    async def upsert(self, organization: Organization) -> Organization: ...


class TeamRepositoryPort(Protocol):
    async def get(self, team_id: TeamId) -> Team | None: ...
    async def list_by_organization(self, organization_id: OrganizationId) -> list[Team]: ...
    async def upsert(self, team: Team) -> Team: ...


class MembershipRepositoryPort(Protocol):
    async def get(self, membership_id: MembershipId) -> Membership | None: ...
    async def get_for_user(self, organization_id: OrganizationId, user_id: UserId) -> Membership | None: ...
    async def list_by_organization(self, organization_id: OrganizationId) -> list[Membership]: ...
    async def list_by_user(self, user_id: UserId) -> list[Membership]: ...
    async def upsert(self, membership: Membership) -> Membership: ...
    async def delete(self, membership_id: MembershipId) -> None: ...


class InvitationRepositoryPort(Protocol):
    async def get(self, invitation_id: InvitationId) -> Invitation | None: ...
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def list_by_organization(self, organization_id: OrganizationId) -> list[Invitation]: ...
    async def upsert(self, invitation: Invitation) -> Invitation: ...
