import { MarketingArticle, ArticleSection } from '@/components/layout/marketing-article'

/** Real mission/architecture facts only — no fabricated team bios, founding story, or company
 * history (none of that exists as real product data, so it isn't invented here). */
export default function AboutPage() {
  return (
    <MarketingArticle
      eyebrow="About"
      title="TitanIQ"
      lede="Sports intelligence built around calibration and explainability, not just a leaderboard of predictions."
    >
      <ArticleSection title="What we build">
        <p>
          TitanIQ is a sports intelligence platform covering Football, Basketball, Baseball, and
          Table Tennis. Every prediction is generated by a market-scoped predictor strategy,
          calibrated against historical outcomes, and shipped with a confidence breakdown and
          feature-level explanation — not a bare probability.
        </p>
      </ArticleSection>
      <ArticleSection title="How it's built">
        <p>
          The platform is a domain-driven, modular backend (sports, ingestion, knowledge graph,
          intelligence, predictions, machine learning, identity/tenancy/billing) behind a single
          FastAPI service, with a real-time-aware React frontend. See{' '}
          <a href="/docs" className="text-accent-primary hover:underline">Documentation</a> for the
          module breakdown.
        </p>
      </ArticleSection>
      <ArticleSection title="Status">
        <p>
          TitanIQ is under active development. Not every capability described in the product
          roadmap is live yet — pages and endpoints are only shipped once backed by real data and
          logic.
        </p>
      </ArticleSection>
    </MarketingArticle>
  )
}
